language: cpp
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
env:
  - CXXFLAGS+=-DEMULATE_LEDBOARD
  - CXXFLAGS+=
script: make
compiler: gcc
